# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ci/docker/using_docker_build/
#
# This template uses one generic job with conditional builds
# for the default branch and all other (MR) branches.

stages:
  - build

docker-build:
  # Use the official docker image.
  image: docker:28-cli
  stage: build
  services:
    - docker:28-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Enable buildx and create builder
    - docker buildx create --use --name multiarch-builder
    - docker buildx inspect --bootstrap
  script:
    # Build for both AMD64 and ARM64
    - docker buildx build 
      --platform linux/amd64,linux/arm64 
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
      --tag $CI_REGISTRY_IMAGE:latest 
      --push .
  after_script:
    - docker buildx rm multiarch-builder
  # # Run this job in a branch where a Dockerfile exists
  # rules:
  #   - if: $CI_COMMIT_BRANCH
  #     exists:
  #       - Dockerfile
  rules:
    - when: always
